function Y = NM80_calibrate_readoutput(output_dir,P)

switch P{27}

    case 'Sectional_normal_force'   
        % in this case the QoI is a vector, returning the time-averaged force at
        % each section
        filename = fullfile(output_dir,'B1n_BEM.txt');
        
        % Read output data generated by AeroModule
        D = readtable(filename,'HeaderLines', 4,"ReadVariableNames",true,...
            "PreserveVariableNames",true); % Reads the variable data from the 
                                           % specified .txt file
        r_a = str2double(D.Properties.VariableNames(3:end)); % Radial stations

        %% Calculate mean
        % column 1 is time, 
        % column 2 is azimuth,
        % columns 3:end correspond to different radial locations
        D_a = mean(D{:,3:end},1); % Mean (average in time) values at different radial stations

        %% Interpolation
        % These values are made available from Danaero experiments
        r_i = [11.87, 17.82, 28.97, 35.53]; % Measurement radial stations
        Y   = spline(r_a,D_a,r_i); % Interpolated data using spline
        
    otherwise
        error(strcat('QoI type unknown; check the turbine file ',P{29}));
        
end