function loads = readNewMexicoModified(filename, dataLines)
%IMPORTFILE Import data from a text file
%  R52P80D935LOADS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  R52P80D935LOADS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  R52P80D935loads = importfile("C:\Users\kriek\Downloads\R52P80D935_loads.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2020 11:27:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Azi", "FaxN", "TorqueNm", "Fn25Npm", "Fn35Npm", "Fn60Npm", "Fn82Npm", "Fn92Npm", "Ft25Npm", "Ft35Npm", "Ft60Npm", "Ft82Npm", "Ft92Npm", "VarName14"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "VarName14", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName14", "EmptyFieldRule", "auto");

% Import the data
loads = readtable(filename, opts);

end