function raw = readNM80(filename, dataLines)
%readNM80 Import data from a text file
%  RAW = readNM80(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  RAW = readNM80(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  raw = importfile3("C:\Users\kriek\Desktop\windtrue\Experimental\WINDTRUE\raw.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-May-2020 13:00:38

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Fy03", "Fy05", "Fy08", "Fy10"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
raw = readtable(filename, opts);

end