function  samplesChord = computeChord(samples, plotSamples,bladeLength,...
                                      interpolationLocations,referenceChord,...
                                      t0,n,sampledLocations,sampledValues, pc)
% This routine computes the random samples of Chord vector using the purturbed
% control points of NURB curve

% Input arguments
% 'samples' Number of samples of perturbed Chord
% 'plotSamples' 0 for no plot, 1 (default) to plot the generated samples, the baseline curve and the control points
% 'interpolationLocations' Points along the blade length according to ECNAERO module input file 
% 'referenceChord' Reference values of Chord obtained from ECNAERO module input file
% 't0' Knot vector b/w [0,1], the number of resulting basis function is numel(t0)+1
% 'n' NURBS order: 2 for linear B-splines, 3 for Quadratic, so on. The polynomial degree of B-spline is n-1.
% 'sampledLocations' Locations where the value of chord is sample. NOTE: numel(sampleLocations) =  numel(t0) + 1
% 'sampledValues' Vales of chord at sampled location
% 'pc' is vector with each element bw [0,1] representing fraction of perturbation for control points from their baseline value. The numel(pc) = numel(sampledLocations)  

% Output argument
% 'samplesChord' are samples of Chord generated by perturbing the baseline control points. Each row corresponds to one sample.

if nargin < 3 % Default function argument values corresponding to NM80 turbine
    plotSamples = 1;
    bladeLength = 38.8; % To normalize the blade length bw [0,1]   
    interpolationLocations = [0 2 4 6 8 10 12 14 16 18 20 22 ...
                          24 26 28 30 32 34 36 37 38 38.4 38.8]; 
                      
    referenceChord = [2.42 2.48 2.65 2.81 2.98 3.14 3.17 2.99 2.79 2.58 2.38 ...
                  2.21 2.06 1.92 1.8 1.68 1.55 1.41 1.18 0.98 0.62 0.48 0.07]; 
             
    t0 = [0 0.15 0.3 0.51 0.7 0.87 0.95 1]; 
    n = 3;
    sampledLocations = [0 4 10 16 20 30 34 37 38.8]; 
    sampledValues = [2.42 2.65 3.14 2.79 2.38 1.68 1.41 0.98 0.07]; 
    pc = 0.2*ones(numel(sampledLocations),1);
end

interpolationLocations = interpolationLocations/bladeLength; % Normalized between [0,1]
sampledLocations = sampledLocations/bladeLength; % Normalized between [0,1]


c = getControlPoints(sampledLocations,sampledValues,t0,n); % control points for NURB curve
t = [t0(1)*ones(1,n-1) t0 t0(end)*ones(1,n-1)]; % padded knot vector obtained by padding n-1 elements at front and end. 
j = 0: numel(t)- n-1; % Index of B-spline from 0 =< j < numel(t)-n

samplesChord = zeros(1,numel(interpolationLocations)); % 'sampleChord' is the function values of NURB curve interpolated at sampleLocations

for i = 1:numel(j)
    [y,interpolationLocations] = bspline_basis(j(i),n,t,interpolationLocations);
    samplesChord = samplesChord + c(i)*y;
end

if plotSamples == 1
    % Plot to check the Chord variation along the blade span. This can be used to 
    % select the knot locations        
    plot(interpolationLocations,referenceChord,'linewidth',2) 
    hold on
    plot(sampledLocations,c,'marker','o','linewidth',2) % plot control points
    plot(sampledLocations,sampledValues,'marker','x','markersize',8,'linestyle','none','linewidth',2) % plot sampled points
    plot(interpolationLocations,samplesChord,'linewidth',2,'color','g')
end
samplesChord = perturbNURBS(t0,n,interpolationLocations,c, pc,samples);

if plotSamples == 1
    plot(interpolationLocations,samplesChord','color','k','linestyle','--','HandleVisibility','off')
    plot(interpolationLocations,samplesChord(1,:),'color','k','linestyle','--')
    legend('reference Chord','control points','sampled data', 'NURB curve','random samples')
    hold off
end
return