function plotHandle = uq_MCMC_plot(plotHandle,plotStep,plotParameters,Sample)
% UQ_PLOTMCMC produces trace plots of the sample points generated by
% different MCMC algorithms.
%
%   UQ_MCMC_PLOT(PLOTHANDLE, PLOTSTEPS, PLOTPARAMETERS, SAMPLE) plots the
%   trace plots of PLOTPARAMETERS parameters in the SAMPLE array from 1
%   until PLOTSTEPS to the plot object stored in PLOTHANDLE. IF PLOTHANDLE
%   is empty, a new plot is generated.
%
%   PLOTHANDLE = UQ_MCMC_PLOT(PLOTHANDLE, PLOTSTEPS, PLOTPARAMETERS, SAMPLE)
%   also returns the PLOTHANDLE handle of the used plot.
%   
%   See also: UQ_MH, UQ_AM, UQ_HMC, UQ_AIES

% INITIALIZE PLOT
if isempty(plotHandle)
    % first time plot function is called
    firstPlot = true;
else
    firstPlot = false;
end

% fontsize
fs = 12;

% loop over plot parameters
for ii = 1:length(plotParameters)
    % sample points that will show up in the next plot
    sampleRange = 1:plotStep;
    sampleFraction = reshape(permute(Sample(sampleRange,plotParameters(ii),:),...
        [2 1 3]),length(sampleRange),[]);
    % sampleFraction = squeeze(Sample(sampleRange,plotVariable(ii),:))';
    % KS density
    [f,xi] = ksdensity(reshape(sampleFraction,[],1));
    
    if firstPlot
        figure('Color','white');
        % first subplot for trace
        subplot(1,2,1)
        plotHandle{ii,1} = plot(sampleRange,sampleFraction); 
        % retreive ylim
        ylimTrace = ylim;
        % label axis
        uq_setInterpreters(gca)
        xlabel('Steps','Fontsize',fs+2)
        ylabel(strcat('$\mathrm{x_{',num2str(plotParameters(ii)),'}}$'),...
            'Fontsize', fs+2)
        grid on
        box on
        set(gca, 'LineWidth', 2, 'Fontsize', fs)
        % second subplot for KDE
        subplot(1,2,2)
        plotHandle{ii,2} = plot(f,xi);
        % set ylim
        ylim(ylimTrace)
        % label axis
        uq_setInterpreters(gca)
        xlabel(strcat('$\mathrm{p(x_{',num2str(plotParameters(ii)),'})}$'),...
            'Fontsize', fs+2)
        ylabel(strcat('$\mathrm{x_{',num2str(plotParameters(ii)),'}}$'),...
            'Fontsize', fs+2)
        grid on
        box on
        set(gca, 'LineWidth', 2, 'Fontsize', fs)
        drawnow();
    else
        % first subplot for trace
        for jj = 1:length(plotHandle{ii,1})
            set(plotHandle{ii,1}(jj),'xdata',sampleRange,'ydata',sampleFraction(:,jj))
        end
        % retreive ylim
        ylimTrace = ylim;
        % second subplot for KDE
        set(plotHandle{ii,2},'xdata',f,'ydata',xi)
        % set ylim
        ylim(ylimTrace)
        drawnow()
    end
    grid on
    box on
    uq_setInterpreters(gca)
    set(gca, 'LineWidth', 2, 'Fontsize', fs)
end

