function output = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OUTPUT1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  OUTPUT1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  output1 = importfile("C:\Users\kriek\Desktop\windtrue\sensitivity_analysis\AEROmodule\NM80_calibrate\output\output.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Apr-2020 10:16:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["r_i", "aero_data"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
output = readtable(filename, opts);

end